apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "citizen-service-api.fullname" . }}
  labels:
    {{- include "citizen-service-api.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "citizen-service-api.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "citizen-service-api.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: citizen-service-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 5000
              protocol: TCP

          envFrom:
            - configMapRef:
                name: {{ include "citizen-service-api.fullname" . }}-config

          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: SECRET_KEY

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
