apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizen-service-api
  labels:
    app: citizen-service-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: citizen-service-api

  template:
    metadata:
      labels:
        app: citizen-service-api

    spec:
      containers:
        - name: citizen-service-api
          image: citizen-service-api:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: citizen-service-config

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
